import React from 'react';
import { Sparkles, TrendingDown, Activity, Cpu } from 'lucide-react';

// ─── Gemini Telemetry Bar ────────────────────────────────────────────────────
export function GeminiTelemetry({
  telemetry, metadata, lastUpdate, isAiMode
}: {
  telemetry: any;
  metadata: any;
  lastUpdate?: number;
  isAiMode?: boolean;
}) {
  const counts = telemetry ?? { total_predictions: 0, total_decisions: 0 };
  const meta = metadata ?? {};
  const geminiCalls = meta.gemini_calls_count ?? 0;
  const geminiDec = meta.gemini_decisions_count ?? meta.decision_count ?? 0;
  const predictions = meta.prediction_count ?? counts.total_predictions ?? 0;
  const aiMode = meta.ai_mode ?? (isAiMode ? 'active' : 'disabled');

  return (
    <div className="glass-panel flex flex-col md:flex-row justify-between items-center gap-4 bg-gradient-to-r from-blue-900/20 to-purple-900/20 border border-purple-500/30">
      {/* Brand */}
      <div className="flex items-center gap-3">
        <Sparkles className="w-6 h-6 text-purple-400 animate-pulse flex-shrink-0" />
        <div>
          <h2 className="text-sm font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
            Powered by Google Gemini AI
          </h2>
          <p className="text-[10px] text-gray-500 tracking-widest uppercase">
            {aiMode === 'active' ? '🟢 AI Mode: Active' : '⚙️ AI Mode: Disabled (Simulation Only)'}
            {lastUpdate && ` • Updated ${new Date(lastUpdate * 1000).toLocaleTimeString()}`}
          </p>
        </div>
      </div>

      {/* Counters */}
      <div className="flex gap-6 flex-wrap justify-center">
        <Stat label="Gemini Calls" value={geminiCalls} color="text-purple-400" />
        <Stat label="AI Decisions" value={geminiDec} color="text-emerald-400" />
        <Stat label="Predictions" value={predictions} color="text-blue-400" />
        <Stat label="Wait Reduced" value={`${counts.wait_time_reduced_percentage ?? 0}%`} color="text-amber-400" />
      </div>
    </div>
  );
}

function Stat({ label, value, color }: { label: string; value: any; color: string }) {
  return (
    <div className="text-center min-w-[72px]">
      <div className={`text-xl font-bold ${color}`}>{String(value)}</div>
      <div className="text-[10px] text-gray-500 uppercase tracking-wide">{label}</div>
    </div>
  );
}

// ─── Impact Metrics Panel ────────────────────────────────────────────────────
export function ImpactMetrics({
  aiTelemetry, aggregateImpact
}: {
  aiTelemetry?: any;
  aggregateImpact?: any;
}) {
  // Prefer live computed telemetry; fall back to Gemini's own aggregate_impact
  const waitReduced = Math.max(
    aiTelemetry?.wait_time_reduced_percentage ?? 0,
    aggregateImpact?.wait_time_reduction ?? 0
  );
  const balanced = Math.max(
    aiTelemetry?.crowd_balanced_percentage ?? 0,
    aggregateImpact?.load_balanced ?? 0
  );

  return (
    <div className="glass-panel flex flex-col justify-center gap-4 h-full border border-[#2a2a2a]">
      <h3 className="text-gray-400 text-sm font-medium flex items-center gap-2 mb-1">
        <TrendingDown className="w-4 h-4 text-emerald-400" /> AI Impact Tracking
        <span className="ml-auto text-[9px] text-gray-600 uppercase tracking-widest">Generated by Google Gemini AI</span>
      </h3>

      <MetricBar label="Wait Time Reduced By" value={waitReduced} color="emerald" unit="%" />
      <MetricBar label="Crowd Load Balanced" value={balanced} color="cyan" unit="%" />
    </div>
  );
}

function MetricBar({ label, value, color, unit }: { label: string; value: number; color: string; unit: string }) {
  const colorMap: Record<string, string> = {
    emerald: 'text-emerald-400 bg-emerald-500',
    cyan: 'text-cyan-400 bg-cyan-500',
  };
  const textColor = colorMap[color]?.split(' ')[0] ?? 'text-gray-400';
  const barColor = colorMap[color]?.split(' ')[1] ?? 'bg-gray-500';

  return (
    <div className="bg-[#1C1C1C] rounded-lg p-3 border border-gray-800">
      <div className="flex justify-between items-baseline mb-2">
        <div className="text-xs text-gray-500">{label}</div>
        <div className={`text-2xl font-bold ${textColor}`}>{value}{unit}</div>
      </div>
      <div className="w-full bg-gray-800 rounded-full h-1.5">
        <div
          className={`${barColor} h-1.5 rounded-full transition-all duration-1000`}
          style={{ width: `${Math.min(value, 100)}%` }}
        />
      </div>
    </div>
  );
}

// ─── Stadium Pulse Gauge ──────────────────────────────────────────────────────
export function PulseGauge({ score }: { score: number }) {
  const getColor = (s: number) => {
    if (s < 40) return { text: 'text-emerald-400', stroke: 'stroke-emerald-400' };
    if (s < 75) return { text: 'text-amber-400', stroke: 'stroke-amber-400' };
    return { text: 'text-red-500', stroke: 'stroke-red-500 animate-pulse' };
  };

  const { text, stroke } = getColor(score);
  const clamped = Math.min(Math.max(score, 0), 100);
  const dashArray = `${clamped}, 100`;

  return (
    <div className="glass-panel flex flex-col relative overflow-hidden h-full">
      <h3 className="text-gray-400 text-sm font-medium mb-4 flex items-center gap-2">
        <Activity className="w-4 h-4" /> Stadium Pulse Score
      </h3>

      <div className="flex-1 flex flex-col items-center justify-center">
        <div className="relative w-32 h-32">
          <svg viewBox="0 0 36 36" className="w-full h-full transform -rotate-90">
            <path className="stroke-gray-700" fill="none" strokeWidth="3"
              d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
            <path className={`${stroke} transition-all duration-1000 ease-out`} fill="none" strokeWidth="3"
              strokeDasharray={dashArray}
              d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
          </svg>
          <div className="absolute inset-0 flex items-center justify-center">
            <span className={`text-3xl font-bold ${text}`}>{score}</span>
          </div>
        </div>
        <p className="mt-3 text-xs text-gray-500 text-center max-w-[80%]">
          Aggregate stress index based on density variance and fill rates.
        </p>
      </div>
    </div>
  );
}
